name: grid
description: A grid css framework
version: 0.1.0
environment:
    sdk: '>=2.0.0-dev.65.0 <3.0.0'

dev_dependencies:
  build_runner: 0.10.0
  build_web_compilers: 0.4.1
  sass_builder: 2.1.1